columns:
  input:
    f_text_0:
      type: "string"
      module_url: "https://tfhub.dev/google/universal-sentence-encoder-large/3"
      # dan_module_url = "https://tfhub.dev/google/universal-sentence-encoder/2"
    f_text_1:
      type: "string"
      module_url: "https://tfhub.dev/google/universal-sentence-encoder-large/3"
    f_int_0:
      type: "categorical"
      hash_bucket_size: 100
      embedding_dimensions: 100
  output:
    f_float_0:
      type: "float"
      min_value: 0
      max_value: 1
    f_int_1:
      type: "categorical"
      hash_bucket_size: 100
      embedding_dimensions: 100
use_cache: false
train: true
batch_size: 100
epochs: 5
profile: true
device: "/device:GPU:0" # "/cpu:0"
model_load_bucketfs_path:
model_save_bucketfs_url: "http://w@write:localhost:6583/default/tensorflow/save"